"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _get_allowed_hosts():
    configured_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
    if configured_hosts.strip():    
        return [
            host.strip()
            for host in configured_hosts.split(",")
            if host.strip()
        ]

    return [
        "127.0.0.1",
        "localhost",
        "[::1]",
        "0.0.0.0",
        "host.docker.internal",
        "testserver",
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+)otfznm$!^qvu-f38l0+f54lyx#47t7mp!lu%bm=v6a_36*8-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = _get_allowed_hosts()


# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    'employees',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = os.environ.get("DATABASE_URL")
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

CORS_ALLOW_ALL_ORIGINS = True

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_ADMIN_USERNAME = os.environ.get("DEFAULT_ADMIN_USERNAME", "admin")
DEFAULT_ADMIN_PASSWORD = os.environ.get("DEFAULT_ADMIN_PASSWORD", "Admin@123")
DEFAULT_ADMIN_EMAIL = os.environ.get("DEFAULT_ADMIN_EMAIL", "admin@example.com")
DEFAULT_SALES_EXECUTIVE_USERNAME = os.environ.get("DEFAULT_SALES_EXECUTIVE_USERNAME", "salesexec")
DEFAULT_SALES_EXECUTIVE_PASSWORD = os.environ.get("DEFAULT_SALES_EXECUTIVE_PASSWORD", "SalesExec@123")
DEFAULT_SALES_EXECUTIVE_EMAIL = os.environ.get("DEFAULT_SALES_EXECUTIVE_EMAIL", "salesexec@example.com")
DEFAULT_LEAD_SALES_USERNAME = os.environ.get("DEFAULT_LEAD_SALES_USERNAME", "leadsales")
DEFAULT_LEAD_SALES_PASSWORD = os.environ.get("DEFAULT_LEAD_SALES_PASSWORD", "LeadSales@123")
DEFAULT_LEAD_SALES_EMAIL = os.environ.get("DEFAULT_LEAD_SALES_EMAIL", "leadsales@example.com")
DEFAULT_HOD_USERNAME = os.environ.get("DEFAULT_HOD_USERNAME", "hod")
DEFAULT_HOD_PASSWORD = os.environ.get("DEFAULT_HOD_PASSWORD", "Hod@12345")
DEFAULT_HOD_EMAIL = os.environ.get("DEFAULT_HOD_EMAIL", "hod@example.com")
DEFAULT_MD_USERNAME = os.environ.get("DEFAULT_MD_USERNAME", "md")
DEFAULT_MD_PASSWORD = os.environ.get("DEFAULT_MD_PASSWORD", "Md@12345")
DEFAULT_MD_EMAIL = os.environ.get("DEFAULT_MD_EMAIL", "md@example.com")
DEFAULT_DOCUMENT_CONTROLLER_USERNAME = os.environ.get(
    "DEFAULT_DOCUMENT_CONTROLLER_USERNAME",
    "documentcontroller",
)
DEFAULT_DOCUMENT_CONTROLLER_PASSWORD = os.environ.get(
    "DEFAULT_DOCUMENT_CONTROLLER_PASSWORD",
    "DocumentController@123",
)
DEFAULT_DOCUMENT_CONTROLLER_EMAIL = os.environ.get(
    "DEFAULT_DOCUMENT_CONTROLLER_EMAIL",
    "documentcontroller@example.com",
)
DEFAULT_OPERATION_HEAD_USERNAME = os.environ.get(
    "DEFAULT_OPERATION_HEAD_USERNAME",
    "storemanager",
)
DEFAULT_OPERATION_HEAD_PASSWORD = os.environ.get(
    "DEFAULT_OPERATION_HEAD_PASSWORD",
    "StoreManager@123",
)
DEFAULT_OPERATION_HEAD_EMAIL = os.environ.get(
    "DEFAULT_OPERATION_HEAD_EMAIL",
    "storemanager@example.com",
)
DEFAULT_SITE_ENGINEER_USERNAME = os.environ.get(
    "DEFAULT_SITE_ENGINEER_USERNAME",
    "siteengineer",
)
DEFAULT_SITE_ENGINEER_PASSWORD = os.environ.get(
    "DEFAULT_SITE_ENGINEER_PASSWORD",
    "SiteEngineer@123",
)
DEFAULT_SITE_ENGINEER_EMAIL = os.environ.get(
    "DEFAULT_SITE_ENGINEER_EMAIL",
    "siteengineer@example.com",
)
ADMIN_AUTH_MAX_AGE = int(os.environ.get("ADMIN_AUTH_MAX_AGE", "43200"))
