import type { Metadata } from "next";
import AppFrame from "@/components/app-frame";
import "./globals.css";

export const metadata: Metadata = {
  title: "Bussinessi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppFrame>{children}</AppFrame>
      </body>
    </html>
  );
}
