# Generated by Django 6.0.3 on 2026-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_costestimationsheet_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesservicerequest',
            name='batteryServices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='manufacturingItems',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='modeOfContact',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='requestType',
            field=models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('service', 'Service')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='scopeArea',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='salesservicerequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='salesservicerequest',
            name='itemName',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='salesservicerequest',
            name='phoneNo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesservicerequest',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesservicerequest',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
