# Generated by Django 6.0.3 on 2026-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_salesservicerequest_batteryservices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesservicerequest',
            name='planEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='planStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='planningRemarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='planningType',
            field=models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('quote_after', 'Quote after'), ('quote_as_per_request', 'Quote as per request')], default='', max_length=30),
        ),
    ]
