# Generated by Django 6.0.3 on 2026-03-31 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_salesservicerequest_planenddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotationCode', models.CharField(max_length=20, unique=True)),
                ('quotationDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('quoteValidityDays', models.PositiveIntegerField(default=12)),
                ('revisedNo', models.PositiveIntegerField(default=0)),
                ('attentionName', models.CharField(max_length=120)),
                ('companyName', models.CharField(blank=True, default='', max_length=160)),
                ('referenceNo', models.CharField(blank=True, default='', max_length=20)),
                ('costEstimationNo', models.CharField(blank=True, default='', max_length=20)),
                ('scopeDetails', models.JSONField(blank=True, default=list)),
                ('totalCost', models.FloatField(default=0)),
                ('paymentTermsType', models.CharField(blank=True, default='', max_length=80)),
                ('paymentTerms', models.TextField(blank=True, default='')),
                ('deliveryTermsType', models.CharField(blank=True, default='', max_length=80)),
                ('deliveryTerms', models.TextField(blank=True, default='')),
                ('termsType', models.CharField(blank=True, default='', max_length=100)),
                ('terms', models.TextField(blank=True, default='')),
                ('currencyName', models.CharField(default='India', max_length=100)),
                ('currencyCode', models.CharField(default='INR', max_length=10)),
                ('currencySymbol', models.CharField(default='₹', max_length=10)),
                ('currencyRateToInr', models.FloatField(default=1)),
                ('currencyAmountLabel', models.CharField(default='Rupees', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('costEstimationSheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='employees.costestimationsheet')),
                ('salesServiceRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='employees.salesservicerequest')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
