# Generated by Django 6.0.3 on 2026-04-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_refresh_marine_cost_estimation_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='revisionNo',
            field=models.PositiveIntegerField(db_column='revisionNo', default=0),
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='revisionNo',
            new_name='revisedNo',
        ),
    ]
