# Generated by Django 6.0.3 on 2026-04-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_restore_missing_purchase_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesservicerequest',
            name='rfqCategory',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('quote_of_assessment', 'Quote of assessment'), ('quote_of_completion', 'Quote of completion')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='rfqType',
            field=models.CharField(blank=True, choices=[('workshop', 'Workshop'), ('spare', 'Spare'), ('onsite', 'Onsite')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='salesservicerequest',
            name='salesExecutive',
            field=models.CharField(blank=True, choices=[('sales_executive_1', 'Sales Executive 1'), ('sales_executive_2', 'Sales Executive 2'), ('sales_executive_3', 'Sales Executive 3')], default='', max_length=30),
        ),
    ]
