# Generated by Django 6.0.3 on 2026-04-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_salesservicerequest_rfqcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobCardNo', models.CharField(max_length=20, unique=True)),
                ('jobCardDate', models.DateField()),
                ('planningDate', models.DateField(blank=True, null=True)),
                ('expectedDate', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('deliveryRemark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchaseOrder', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='jobCard', to='employees.purchaseorder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
