# Generated by Django 6.0.3 on 2026-04-08 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0027_jobcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="purchaseOrder",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobCard",
                to="employees.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="jobcard",
            name="quotation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobCard",
                to="employees.quotation",
            ),
        ),
    ]
